baseURL = "/"
languageCode = "en-us"
title = "Alex Antonison"
description = "A place to collect my thoughts."
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Alex Antonison"
    description = "A place to collect my thoughts."
    logo = "favicon/android-chrome-192x192.png"
    twitterAuthor = "@adantonison"
    githubUsername = "alex-antonison"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4
    
[[menu.main]]
  url = "/talk/"
  name = "Talks"
  weight = 5
  
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:adantonison@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/alex-antonison"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/adantonison"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/alexanderantonison"
    name = "linkedin"
    weight = 4