---
title: Ethical use of algorithms with data
author: Alex Antonison
date: '2019-01-21'
slug: ethical-use-of-algorithms-with-data
categories: []
tags:
  - '#ethics'
  - '#machinelearning'
  - '#wordembeddings'
  - '#imagerecognition'
  - '#algorithmicbias'
---

### Preface

Before I talk about my views on ethics in the realm of Data Science, I first want to talk about how I got into Data Science.  After spending two years analyzing data doing a lot of scripting and SQL, I was at a point in my career where I wanted to pick a path.  After a bit of searching I landed on the field of Data Science since it is a perfect fit with my love of statistics and working with data.  Like with anything, my first approach was to scour the internet and try and find as much information on the topic as possible.  I took a few Coursera courses, followed _top data scientists on twitter_, read blogs, and listened to podcasts.  More often than not, the topics were usually around applications of machine learning, interesting papers, or interviews.  However, periodically there was something that would catch my eye on a topic like "gender biased word embeddings" and quickly I realized that although Data Science has large potential for good, it also has a large potential to either harm individuals or entire communities.  Once I was turned onto this topic, I started to actively search for these issues and came upon a couple of good articles that covered a wide variety of issues such as [Biased Algorithms Are Everywhere, and No One Seems to Care](https://www.technologyreview.com/s/608248/biased-algorithms-are-everywhere-and-no-one-seems-to-care/)

However, before I go any further, I would like to introduce two concepts that are at the center of this post.

- **Machine Learning:** "Machine learning algorithms build a mathematical model of sample data, known as "training data", in order to make predictions or decisions without being explicitly programmed to perform the task." - [https://en.wikipedia.org/wiki/Machine_learning](https://en.wikipedia.org/wiki/Machine_learning)
- **Algorithmic Bias:** "Algorithmic bias occurs when a computer system reflects the implicit values of the humans who are involved in coding, collecting, selecting, or using data to train the algorithm." - [https://en.wikipedia.org/wiki/Algorithmic_bias](https://en.wikipedia.org/wiki/Algorithmic_bias)

With that covered, to the main part of this post where I talk about a handful of examples where things or products were built without ethical considerations.

### Gender biased word embeddings

Okay, so before I talk about how a [word embedding](https://en.wikipedia.org/wiki/Word_embedding) can be gender biased, first I would like to talk about what is a word embedding.  A word embedding is a very useful tool where a model can represents the relationships between words as mathematical values to allow for associations such as "man:king" with "woman:queen" and "paris:france" with "tokyo:japan".  Cool right? However, this bias has been extended to "man:programmer" with "woman:homemaker". Not cool.  A common model used is Word2Vec developed by Google back in 2013 trained on Google News texts.  Unfortunately because the data this model was trained on was gender biased, so are the results.  But there is hope! Researchers have done work to both quantify the bias and come up with methods to "debias" the embeddings in [
Man is to Computer Programmer as Woman is to Homemaker? Debiasing Word Embeddings](https://arxiv.org/abs/1607.06520).  For more on this, I recommend [How Vector Space Mathematics Reveals the Hidden Sexism in Language](https://www.technologyreview.com/s/602025/how-vector-space-mathematics-reveals-the-hidden-sexism-in-language/).

### Mortage loan interest rate bias

I find this to be a more traditional instance where financial institutions set out to use "big data" with "machine learning" to find ways to infer interest rates based on geography or characteristics of applicants.  This is referred to as "Algorithmic Strategic Pricing". A result of this, [based on a study done by UC Berkly](http://faculty.haas.berkeley.edu/morse/research/papers/discrim.pdf), African Americans and Latino borrowers pay more on purcahse and refinance loans than White and Asian ethnicity borrowers. "The lenders may not be specifically targeting minorities in their pricing schemes, but by profiling non-shopping applicants they end up targeting them" said [Adair Morse](http://faculty.haas.berkeley.edu/morse/).

For more information, you can check out [Minority homebuyers face widespread statistical lending discrimination, study finds](http://newsroom.haas.berkeley.edu/minority-homebuyers-face-widespread-statistical-lending-discrimination-study-finds/) or the study itself [Consumer-Lending Discrimination in the Era of FinTech](http://faculty.haas.berkeley.edu/morse/research/papers/discrim.pdf)

### Image recognition bias

### Microsoft Tay twitter bot

### Facebook Cambridge Analytica scandal

### Additional sources

If you are still interested in looking more into this topic, I highly recommend checking out the following:

- Articles
  - [“We’re in a diversity crisis”: cofounder of Black in AI on what’s poisoning algorithms in our lives](https://www.technologyreview.com/s/610192/were-in-a-diversity-crisis-black-in-ais-founder-on-whats-poisoning-the-algorithms-in-our/)
  - [Machine bias risk assessments in criminal sentencing](https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing)
- Podcasts
  - [Data Skeptic - Data Ethics](https://dataskeptic.com/blog/episodes/2018/data-ethics)
  - [Linear Digressions - Facial recognition, society, and the law](http://lineardigressions.com/episodes/2018/12/30/facial-recognition-society-and-you)
  - [Linear Digressions - When is open data too open?](http://lineardigressions.com/episodes/2018/2/25/when-is-open-data-too-open)
- Books
  - [Weapons of Math Destruction](https://weaponsofmathdestructionbook.com/)